### ISSUE TITLE
Second Part - Explaining Noto

### ISSUE THREAD

**Issue by luknl** [luknl/hetic-p2019-12-noto#6]
## Description

The second part of the experiment highlights Google and the challenge that it makes to society. Noto will be deployed on all the ecosystems. For Google, writing is a major issue, this is why Noto was created. This part takes the form of a web documentary.
## Tasks
- [x] wireframes @Pierre-Brice 
- [x] UI @Pierre-Brice  
- [x] Validate @luknl 
- [x] Writing / Content @CharlesMangwa 
- [x] Dev @yohan-atlan 
- [x] Validate 2 @luknl

**Comment by CharlesMangwa** [comment]
In ENG por favor :/ …
